export const REPOSITORIES = {
	DATA_SOURCE: 'DATA_SOURCE',
	USER_REPO: 'USER_REPOSITORY',
	POST_REPO: 'POST_REPOSITORY',
	POST_MEDIA_REPO: 'POST_MEDIA_REPOSITORY',
	POST_LIKES_REPO: 'POST_LIKES_REPOSITORY'
};
